### ISSUE TITLE
[Bug]: Water Bottle getting a colored retexture

### ISSUE THREAD

**Issue by ffuentesm** [Fuzss/distinguishedpotions#6]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20

### Mod Version (Required)

7.0.0

### Notes (Required)

The option to give a unique color to non-water bottles is also affecting the water bottle
![image](https://github.com/Fuzss/distinguishedpotions/assets/44974827/f69c3098-29a3-4469-b1b6-90ac6743d979)

The option should not affect plain water bottles

**Comment by Fuzss** [comment]
Thanks for reporting! This is fixed in the 1.20.1 port. I've dropped support for 1.20 in favor of 1.20.1, so the fix won't be backported.

**Comment by Zelly9191** [comment]
This issue is still happening the awkward potions, water bottles, and other base potions that should be blue are white for me. the same color as water breathing. I don't have a log or a screenshot at this specific minute but ill grab them later. (i know this is very unhelpful but i promise ill post more info soon with actually helpful info).

for now i can give you this info:

Minecraft version: 1.21.1
Modloader: Neoforge 21.1.217
Mod version: DistinguishedPotions-v21.1.1
Updated from: N/A
OS: Linux Steam OS
Type: Single Player (not open to Lan)
Client or Server side issue: Unknown

**Comment by Zelly9191** [comment]
not this mod my bad ignore my previous comment
